infodoc/urls.py
import autocomplete_light
autocomplete_light.autodiscover()

from django.conf.urls import patterns, include, url
from django.views import generic
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

from datarecord.views import *
from csmuser.views import *
from datarecord.filter_list import *
from datarecord.context_processors import *
from postman.urls import *
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import CreateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
     (r'^$', main),
     #~ (r'^forms_incoming/$', forms_correspondence_incoming),
     #~ (r'^forms_outgoing/$', forms_correspondence_outgoing),
     #~ (r'^preview_signature/(?P<name>\d{1,9})/$', preview_signature),
     #~ (r'^list_correspondense/(?P<name>\d{1,9})/$', preview_signature),
     #~ (r'^signature_save/$', signature_save),
     (r'^no_sign/$', no_sign),
     (r'^no_works/$', no_works),
     (r'^sign_true/$', sign_true),
     (r'^view1/$', view1),
     (r'^view2/$', view2),
     (r'^forms_incoming/$', DocCreate_incoming.as_view()),
     (r'^forms_outgoing/$', DocCreate_outgoing.as_view()),
     (r'^create_incoming/$', DocCreate_incoming.as_view()),
     (r'^create_outgoing/$', DocCreate_outgoing.as_view()),
     (r'^edit/(?P<pk>\d{1,9})/$', EditView.as_view()),
     (r'^update/(?P<pk>\d{1,9})/$', EditView.as_view()),
     (r'^edit_profile/(?P<pk>\d{1,9})/$', EditProfile.as_view()),
     (r'^update_profile/(?P<pk>\d{1,9})/$', EditProfile.as_view()),
     (r'^preview_signature/(?P<pk>\d{1,9})/$', SignatureView.as_view()),
     (r'^preview_doc/(?P<pk>\d{1,9})/$', Preview_doc.as_view()),
     (r'^signature_save/(?P<pk>\d{1,9})/$', SignatureView.as_view()),
     (r'^void/(?P<pk>\d{1,9})/$', VoidView.as_view()),
     (r'^void_save/(?P<pk>\d{1,9})/$', VoidView.as_view()),
     (r'^by_void/(?P<cor_type>\d{1})/(?P<cor_identity>\d{1})/$', by_void.as_view()),
     (r'^by_void/(?P<pk>\d{1,9})/$', by_void.as_view()),
     #~ (r'^void_date/(?P<control_types>\w+)/$', FilterVoid_by_date.as_view()),
     (r'^by_control/(?P<control_types>\w+)/$', by_control.as_view()),
     #~ (r'^by_date1/(?P<datetime_doc>\d{1,9})/$', by_date.as_view()),
     url(r'^by_date/(?P<year>\w+)/(?P<month>\w+)/$', by_date.as_view(), name='by_date'),
     (r'^by_all/$', by_all.as_view()),
     (r'^today/$', today.as_view()),
     (r'^yesterday/$', yesterday.as_view()),
     (r'^week/$', week.as_view()),
     (r'^list_incoming/(?P<cor_type>\d{1})/$', list_incoming.as_view()),
     (r'^list_incoming/(?P<cor_type>\d{1})/(?P<cor_identity>\d{1})/$', list_incoming.as_view()),
     (r'^list_outgoing/(?P<cor_type>\d{1})/(?P<cor_identity>\d{1})/$', list_outgoing.as_view()),
     (r'^list_outgoing/(?P<cor_type>\d{1})/$', list_outgoing.as_view()),
     url(r'^accounts/', include('django.contrib.auth.urls')),
     #~ url(r'^accounts/profile/$', RedirectView.as_view(url='/')), 
     url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
     url(r'autocomplete/', include('autocomplete_light.urls')),
     (r'^messages/', include('postman.urls')),
     #~ url(r'^view/(?P<message_id>[\d]+)/$', 'view', {'form_class': MyCustomQuickReplyForm}, name='postman_view'),
     url(r'^admin/', include(admin.site.urls)),
     #~ url(r'widget/add/$', generic.CreateView.as_view(model=Widget, form_class=WidgetForm)),
     #~ url(r'widget/(?P<pk>\d+)/update/$', generic.UpdateView.as_view(model=Widget, form_class=WidgetForm), name='widget_update'),
     #~ url(r'widget/add/$', generic.CreateView.as_view(model=Correspondence, form_class=forms_cor)),
     #~ url(r'widget/(?P<pk>\d+)/update/$', generic.UpdateView.as_view(model=Correspondence, form_class=forms_cor), name='widget_update'),
)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('django.contrib.auth.views',
  url(r'^user/(?P<user_id>\d+)/user_edit/password/$', 'password_change')
)

infodoc/csmuser/models.py
# coding: utf8
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _

# Модифицируем поле email.
# _meta это экземпляр django.db.models.options.Options, который хранит данные о модели.
# Это немного хак, но я пока не нашел более простого способа переопределить поле из базовой модели.
AbstractUser._meta.get_field('email')._unique = True
AbstractUser._meta.get_field('email').blank = False


class Department(models.Model):
    """Наименование отделов"""
    number_dep = models.PositiveIntegerField(max_length=4, verbose_name="Номер відділу", default="")
    name_department = models.CharField(blank=True, null=True, max_length=150, verbose_name="Найменування відділу")
    accessory_department = models.CharField(blank=True, null=True, max_length=50, verbose_name="Приналежність відділу до напрямку")

    class Meta:
        verbose_name = 'Наименование отделов'
        verbose_name_plural = 'Наименование отделов'
        ordering = ['number_dep']
        permissions = (('perms_department', u'права на отделы'),)
    
    def __unicode__(self):
        return str(self.number_dep) +u' - '+self.name_department;
        #~ return '%s' % self.name_department

class UserProfile(AbstractUser):
    patronymic = models.CharField(blank=True, max_length=255, verbose_name="По-батькові")
    position = models.CharField(blank=True, max_length=255, verbose_name="Посада")
    department = models.ForeignKey(Department, blank=True, null=True, related_name = 'depart', verbose_name="Найменування відділу")
    jabber_name = models.CharField(max_length=50, verbose_name="Имя в jabber")
    birthday = models.DateField(_(u'birthday'), blank=True, null=True)

    class Meta:
            verbose_name = 'Сотрудники предриятия'
            verbose_name_plural = 'Сотрудники предриятия'
            ordering = ["username"]
            permissions = (('perms_userprofile', u'права на редактирование сотрудников'),)
    
    def __unicode__(self):  
              return '%s %s %s' % (self.first_name, self.patronymic, self.last_name,)
    
    def get_full_name(self):
        return '%s %s %s' % (self.first_name, self.patronymic, self.last_name,)

    def get_short_name(self):
        return self.username

infodoc/datarecord/models.py
# -*- coding: utf-8 -*-
from django.db import models

from infodoc.csmuser.models import *
from django.core.mail import EmailMessage

from django.db.models import signals
from django.core.mail import send_mail

from django.core import urlresolvers

from django.forms import ModelForm
#~ from django.contrib.auth.models import User

cor_types=((1,u'входящая '), (2,u'исходящая'))
cor_identity=((3,u'местная '), (4,u'иногородняя'))
type_control=(('un_control',u'Не на контролі'), ('control',u'На контролі'), ('del_control',u'Знятий з контролю'))
fix_signature=(('unsigned',u'Не отриманий'), ('partially_signed',u'Отриманий не всіма виконавцями'), ('signed',u'Отриманий'))


class spr_from_metro(models.Model):
    """Підприємства из spr_metro"""
    npr = models.CharField(blank=True, null=True, unique=True, max_length=6, verbose_name="Картка підприємства")
    kok = models.CharField(blank=True, null=True, max_length=50, verbose_name="ЄДРПОУ підприємства")
    iprukr = models.CharField(blank=True, null=True, max_length=255, verbose_name="Найменування підприємства")
    ipr = models.CharField(blank=True, null=True, max_length=255, verbose_name="Найменування підприємства русское")
    
    class Meta:
        verbose_name = 'Предприятия из spr_metro'
        verbose_name_plural = 'Предприятия из spr_metro'
        ordering = ["npr"]
        db_table = 'spr_from_metro'
        permissions = (
        ('perms_spr_metro', u'права на spr_metro'),
        )
    def __unicode__(self):
        return '%s' % self.iprukr


class Correspondence(models.Model):
    """Корреспонденция"""
    datetime_doc = models.DateTimeField(blank=True, verbose_name="Дата реєстрації")
    date_control = models.DateField (blank=True, null=True, verbose_name="Дата зняття з контролю")
    number = models.PositiveIntegerField(blank=True, null=True, verbose_name="Номер документу")
    number_hide = models.PositiveIntegerField(blank=True, null=True)
    number_department = models.ForeignKey('csmuser.Department', blank=True, null=True, verbose_name="Номер відділу")
    number_organization = models.CharField(blank=True, null=True, max_length=10, verbose_name="Номер листа підприємства")
    date_organization = models.DateField (blank=True, null=True, verbose_name="Дата листа підприємства")
    cor_type = models.PositiveIntegerField(choices=cor_types, verbose_name="Тип кореспонденції")
    cor_identity = models.PositiveIntegerField(choices=cor_identity, verbose_name="Приналежність кореспонденції")
    name_pidpr = models.ForeignKey('datarecord.spr_from_metro', blank=True, null=True, verbose_name="Найменування організації")
    new_pidpr = models.CharField(blank=True, null=True, max_length=150, verbose_name="Найменування нової організації")
    theme_cor = models.CharField(blank=True, null=True, max_length=50, verbose_name="Стислий зміст")
    registrator = models.ForeignKey('csmuser.UserProfile', related_name = 'registrator', null=True, blank=True)
    performer = models.ManyToManyField('csmuser.UserProfile', blank=True, null=True, verbose_name="Виконавці")
    checked_email = models.BooleanField(verbose_name="Відмітка про отримання по e-mail")
    control_types = models.CharField(choices=type_control, max_length=25, verbose_name="Контроль документа", default='un_control')
    signature = models.CharField(choices=fix_signature, max_length=25, verbose_name="Відомості про отримання документа", default='unsigned')
    #~ control = models.BooleanField(verbose_name="Відмітка про контроль документа")
    #~ unchecked_control = models.BooleanField(verbose_name="Відмітка про зняття з контролю")
    #~ signature = models.BooleanField(verbose_name="Відмітка про отримання документа")
    fio_signature = models.ManyToManyField('csmuser.UserProfile', related_name = 'fio_signature', blank=True, null=True, verbose_name="ПІБ, які отримали документ")
    OBJECT_DELETE = models.BooleanField(verbose_name="Відмітити для видалення", default=False)
    
    class Meta:
        verbose_name = 'Корреспонденция'
        verbose_name_plural = 'Корреспонденция'
        ordering = ["-datetime_doc"]
        permissions = (
        ('perms_cor_all', u'права общие'),
        ('perms_cor_performer', u'права исполнителей'),
        ('perms_cor_kanc', u'права канцелярии'),
        )
    
    def number_full(self):
        if self.number_department and self.checked_email:
            return '%s/%s (email)' % (self.number, self.number_department.number_dep)
        if self.number_department:
            return '%s/%s' % (self.number, self.number_department.number_dep)
        if self.number and self.checked_email:
            return str(self.number) +u' (email)'
        else:
            return self.number
    
    def number_dep(self):
        return self.number_department.number_dep
    
        #~ if self.number_department and self.checked_email:
            #~ return str(self.number) +u'/'+str(self.number_department) +u' (email)'
        #~ if self.number_department:
            #~ return str(self.number) +u'/'+str(self.number_department)
        #~ if self.number and self.checked_email:
            #~ return str(self.number) +u' (email)'
        #~ else:
            #~ return self.number
            
    def __unicode__(self):
        return '%s' % self.theme_cor;
    
    #~ def save(self):
        #~ for item in UserProfile.objects.all():
            #~ to_email = item.email
            #~ subject = 'бла-бла-бла'
            #~ html_content = '<a href="http://127.0.0.1/edit/%s/">%s</a>' % (self.id, self.theme_cor)
            #~ from_email = 'i@developtolive.com'
            #~ msg = EmailMessage(subject, html_content, from_email, [to_email])
            #~ msg.content_subtype = "html"
            #~ msg.send()
        #~ super(Correspondence, self).save()

#~ def notify_admin(sender, instance, created, **kwargs):
    #~ '''о добавлении нового документа'''
    #~ if created:
       #~ subject = 'New user created'
       #~ message = 'User %s was added' % instance.username
       #~ from_addr = 'no-reply@example.com'
       #~ recipient_list = ('krytopes@gmail.com',)
       #~ send_mail(subject, message, from_addr, recipient_list)
       #~ 
#~ signals.post_save.connect(notify_admin, sender=Correspondence)

infodoc/csmuser/forms.py
# coding: utf8
from models import *
from .models import UserProfile
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm


# Допиливаем форму добавления пользователя. В Meta.model указываем нашу модель.
class AdminUserAddForm(UserCreationForm):

    class Meta:
        model = UserProfile
        fields = ("username", "email", "password1", "password2")

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            UserProfile._default_manager.get(username=username)
        except UserProfile.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])


# Допиливаем форму редактирования пользователя. В Meta.model указываем нашу модель.
class AdminUserChangeForm(UserChangeForm):

    class Meta:
        model = UserProfile

class forms_profile(ModelForm):
    def __init__(self, *args, **kwargs):
        super(forms_profile, self).__init__(*args, **kwargs)
        #~ self.fields['username'].widget.attrs['readonly'] = True
        self.fields['last_login'].widget=forms.HiddenInput()
        self.fields['username'].widget=forms.HiddenInput()
        self.fields['password'].widget=forms.HiddenInput()
        #~ self.fields['groups'].widget=forms.HiddenInput()
        #~ self.fields['user_permissions'].widget=forms.HiddenInput()
        self.fields['is_superuser'].widget=forms.HiddenInput()
        self.fields['is_staff'].widget=forms.HiddenInput()
        self.fields['is_active'].widget=forms.HiddenInput()
        self.fields['date_joined'].widget=forms.HiddenInput()
    class Meta:
        model = UserProfile

infodoc/csmuser/views.py
# -*- coding: utf-8 -*-

from types import *
from models import *
from forms import *

import re

from django.http import HttpResponse
from django.core.context_processors import csrf
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.http import Http404

class EditProfile(UpdateView):
    model = UserProfile
    form_class = forms_profile
    context_object_name = 'list_profile'
    template_name = 'profile/my_profile.html'
    
    @method_decorator(login_required)
    @method_decorator(permission_required('csmuser.perms_userprofile'))
    def dispatch(self, *args, **kwargs):
        return super(EditProfile, self).dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect('/')

infodoc/templates/datarecord/filter_list.html
{% extends "base.html" %}

{% block custom_css %}
<style>
.sidebar {
float:left;
postion:relative;
height: 150px;
width:200px;
padding:10px;
}

.correspondence {
margin-top:-10px;
margin-left:200px;
margin-right:50px;
}
</style>

{% endblock %}

{% block sidebar %}
<div class="sidebar">
    <div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Всього</li>
        <li><a href="/by_all/">Взагалі всі</a></li>
        <li class="nav-header">Анульовані</li>
        <li><a href="/by_void/1/">Взагалі всі</a></li>
        <li><a href="/by_void/1/3/">Вхідна місцева</a></li>
        <li><a href="/by_void/1/4/">Вхідна іногородня</a></li>
        <li><a href="/by_void/2/3/">Вихідна місцева</a></li>
        <li><a href="/by_void/2/4/">Вихідна іногородня</a></li>
        </br>
        <li class="nav-header">Зареєстровано</li>
        <li><a href="/today/">За сьогодня</a></li>
        <li><a href="/yesterday/">За вчора</a></li>
        <li><a href="/week/">За неділю</a></li>
        {{today}}
        {% for item in today %}
            <li><a href="{% url 'by_date' year=item.year month=item.month %}">{{ item|date:'d.m.Y' }}</a></li>
        {% endfor %}
        {% for item in months_choices %}
            <li><a href="{% url 'by_date' year=item.year month=item.month %}">{{ item|date:'F Y' }}</a></li>
        {% endfor %}
        <li class="nav-header">Контроль</li>
        <li><a href="/by_control/un_control/">На не контролі</a></li>
        <li><a href="/by_control/control/">На контролі</a></li>
        <li><a href="/by_control/del_control/">Зняті з контролю</a></li>
    </ul>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="correspondence">
    <h2>{{ title }} {{ filter_list|length }}</h2>
    <h3>{{ caption }}</h3>

<!-- анульовані-->
{% load in_group %}
<table class="table table-bordered">
            <tr class="warning" style='font-weight: bold; text-align:center;'>
              <td type='datetime_doc' class='date_doc'>Дата</td>
              <td type='number' class='number'>Номер</td>
              <td type='number_organization' class='number_organization'>Номер вихідного листа</td>
              <td type='cor_type' class='cor_type'>Тип кореспонденції</td>
              <td type='cor_identity' class='cor_identity'>Приналежність кореспонденції</td>
              <td type='name_pidpr' class='name_pidpr'>Звідки надійшов</td>
              <td type='theme_cor' class='theme_cor'>Стислий зміст</td>
              <td type='performer'  class='performer'>Виконувачі</td>
              <td type='control' class='control'>Відмітка про контроль</td>
              <td type='status' class='status'>Статус підпису</td>
               {% if request.user.is_superuser or user|in_group:"Kanc" %}
              <td type='view_documents' class='view_documents'>Редагування</td>
              {% endif %}
            </tr>

{% load endless %}

     {% paginate 5 filter_list %}
    {% for obj in filter_list %}
            <tr>
            <td>{{obj.datetime_doc|date:"d.m.Y"}}</td>
            <td>{{obj.number_full}}</td>
            <td>{{obj.number_organization}} {{obj.date_organization|date:"d.m.Y"}}</td>
            <td>{{obj.get_cor_type_display}}</td>
            <td>{{obj.get_cor_identity_display}}</td>
            <td>{% if obj.name_pidpr == None %}
                 {{obj.new_pidpr}}
                {% else %}
                {{obj.name_pidpr}}
                {% endif %}
            </td>
            <td>{{obj.theme_cor}}</td>
            <td>{% for item in obj.performer.all %}{{ item }}<br>{% endfor %}</td>
            {% if obj.control_types == 'control'  %}
            <td class= "control">На контроле</td>
            {% elif obj.control_types == 'del_control' %}
            <td class = 'del_control'>Знятий з контролю</td>
            {% elif obj.control_types == 'un_control' %}
            <td></td>
            {% endif %}
            {% if obj.signature == 'unsigned'  %}
            <td class= "uncollected">Не отриманий {% for item in obj.fio_signature.all %}{{ item }}<br>{% endfor %}</td>
            {% elif obj.signature == 'partially_signed' %}
            <td class = 'partially_signed'>Частково отриманий {% for item in obj.fio_signature.all %}{{ item }}<br>{% endfor %}</td>
            {% elif obj.signature == 'signed' %}
            <td class="approved">Отриманий {% for item in obj.fio_signature.all %}{{ item }}<br>{% endfor %}</td>
            {% endif %}
            
            {% if request.user.is_superuser or user|in_group:"Kanc" %}
            <td>
                <p><a href="/edit/{{obj.pk}}" class="label label-info">Редагувати</a></p>
            </td>
            {% endif %}
        </tr>
    
    {% endfor %}
</table>
{% show_pages %}
</div>
{% endblock %}

infodoc/templates/datarecord/forms_incoming.html
{% extends "base.html" %}

    {% load staticfiles %}
    {% block custom_script %}
        <script>
        $(function() {
            $( "#datepicker" ).datepicker();
        });
        </script>
     {% endblock %}
     
    {% block custom_css %}
    <style>
        .forms {
        margin-left:150px;
        margin-right:50px;
        }
    </style>
    {% endblock %}

<body>
    
    
{% block forms %}
<div class='forms'>
<div class="alert alert-info">
<h3>Створення вхідної кореспонденції</h3>
</div>
    <form action="/create_incoming/" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row-fluid">
            <div class="span4">
                  <fieldset>
                    <legend>Номер/дата листа підприємства</legend>
                    {{ form.number}}
                    
                    {{ form.number_hide}}
                    
                    {{form.number_organization.label_tag}}
                    {{ form.number_organization }}
                    
                    {{ form.number_department }}
                    
                    {% if form.date_organization.errors %}
                    <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Введіть дату у вірному форматі</strong>
                        </div>
                    {% endif %}
                    {{form.date_organization.label_tag}}
                    {{ form.date_organization }}
                    
                </fieldset>
            </div><!--/span-->
            
            <div class="span4">
                <fieldset>
                    <legend>Дата реєстрації</legend>
                    {% if form.datetime_doc.errors %}
                        <div class="alert alert-error">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>Введіть дату у вірному форматі</strong>
                        </div>
                    {% endif %}
                    {{form.datetime_doc.label_tag}}
                    {{ form.datetime_doc}}
                    
                    
                    
                </fieldset>
            </div><!--/span-->
            
            
      </div><!--/row-->
        
      <div class="row-fluid">
          <div class="span4">
                <fieldset>
                <legend>Вид документів</legend>
                {{ form.cor_type }}
                
                {% if form.cor_identity.errors %}
                    <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Введіть приналежність кореспонденції</strong>
                    </div>
                {% endif %}
                {{form.cor_identity.label_tag}} {{ form.cor_identity }}
                </fieldset>
                
            </div><!--/span-->
          
            <div class="span4">
                <fieldset>
                <legend>Виконавці</legend>
                {{ form.registrator }}
                
                {{ form.performer }}
                </fieldset>
            </div><!--/span-->
            
      </div><!--/row-->
      
      <div class="row-fluid">
          
            
            <div class="span4">
                
                <fieldset>
                <legend>Тема та позначки</legend>
                 {% if form.theme_cor.errors %}
                    <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Введіть тему документа</strong>
                    </div>
                {% endif %}
                
                {{form.theme_cor.label_tag}}
                {{ form.theme_cor }}

                {{form.control_types.label_tag}}
                {{form.control_types}}

                {{form.checked_email.label_tag}}
                {{form.checked_email}}
                
                {{form.signature}}
                </fieldset>
            </div><!--/span-->
            
             <div class="span4">
                <fieldset>
                <legend>Організація</legend>
                {% if form.name_pidpr.errors %}
                    <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>Введіть підприємство</strong>
                    </div>
                {% endif %}
                <div class="accordion" id="accordion2">
                <div class="accordion-group">
                <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                {{form.name_pidpr.label_tag}}
                </a>
                </div>
                <div id="collapseOne" class="accordion-body collapse in">
                <div class="accordion-inner">
                {{ form.name_pidpr }}
                </div>
                </div>
                </div>
                <div class="accordion-group">
                <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Якщо нове підприємство &raquo;
                </a>
                </div>
                <div id="collapseTwo" class="accordion-body collapse">
                <div class="accordion-inner">
                {{form.new_pidpr.label_tag}}
                {{ form.new_pidpr }}
                </div>
                </div>
                </div>
                </div>
                </fieldset>
            </div><!--/span-->
            
      </div><!--/row-->
    
       
</br>
        <input type="submit" class='btn btn-primary' value="Сохранить">
    </form>
        {% include 'autocomplete_light/static.html' %}
{% endblock %}  
</div>
</body>

infodoc/templates/datarecord/preview_doc.html
{% extends "base_for_preview.html" %}
<div class="header">
<h3>Отримання документу</h3>
</div>
<div class="modal-body">
{% block preview %}

<form action="/signature_save/{{object.id}}/" method="post" enctype="multipart/form-data">{% csrf_token %}
<p>Документ <strong>№{{object.number}}</strong></p>
<p>Який надійшов від <strong>{{object.name_pidpr}}</strong></p>
<p>Зареєстрований <strong>{{ object.datetime_doc|date:"d.m.Y" }}</strong></p>
<p>з темою <strong>{{ object.theme_cor }}</strong></p>
<p>Виконувачі:<br><strong>{% for item in object.performer.all %}{{ item }}<br>{% endfor %}</strong></p>
<p>Статус документа: <strong>{{object.get_signature_display}}</strong></p>
<h5>Якщо ви отримали цей документ у паперовому вигляді натисніть "Отримати"</h5>
<p style = "width: 50%; margin: 0 auto; text-align: justify;">
<button class="btn btn-primary" type="submit">Отримати</button>
<a href='/' class="btn  btn-inverse" >На головну</a>
</p>
</form>

</div>
{% endblock %}

infodoc/templates/datarecord/preview_signature.html
<div class="modal-header">
<a class="close" data-dismiss="modal">&times;</a>
<h3>Отримання документу</h3>
</div>
<div class="modal-body">
{% block signature %}

<p>Вы збираєтесь отримати документ <strong>{{object.number}}</strong> під іменем <span class="label label-important">{{ request.user.get_full_name }}</span></p>
<p>Який надійшов від <strong>{{object.name_pidpr}}</strong></p>
<p>Зареєстрований <strong>{{ object.datetime_doc|date:"d.m.Y" }}</strong></p>
<p>з темою <strong>{{ object.theme_cor }}</strong></p>
<p>Виконувачі:<br><strong>{% for item in object.performer.all %}{{ item }}<br>{% endfor %}</strong></p>

{% endblock %}
<form action="/signature_save/{{object.id}}/" method="post" enctype="multipart/form-data">{% csrf_token %}
</form>
</div>
<div class="modal-footer">
<a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Отримати</a>
<a class="btn" data-dismiss="modal">Закрити</a>
</div>

infodoc/templates/datarecord/signature_save.html
{% extends "base.html" %}

<body>
{% block content %}
        
        <h3>Документ отриманий</h3>
        
{% endblock %}
</body>